miEmpresa := Empresa new.
miEmpresa init.

"persona := Usuario new.
persona dni: 5.
miEmpresa altaUsuario: persona."


"persona := Usuario new.
persona dni: 2.
miEmpresa altaUsuario: persona."

"persona := Usuario new.
persona dni: 69.
miEmpresa altaUsuario: persona."
miEmpresa altaUsuario.
miEmpresa altaUsuario.
miEmpresa altaUsuario.
"Ejecutar esto debería producir los mismos resultados. La teoría dada en clase parece indicar que esta es la forma de hacer las altas -TM"
miEmpresa buscarUsuario: 3.
"en efecto, buscarUsuario sigue sin funcionar -TM"